robotom/main/urls.py
from django.conf.urls import url
from django.conf import settings
from main import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^group1/', views.group1, name='group_1'),
    url(r'^group2/', views.group2, name='group_2'),
    url(r'^group3/', views.group3, name='group_3'),

    url(r'^accounts/profile/$', views.profile_view, name='profile'),
    url(r'^accounts/confirm/(?P<activation_key>[0-9A-Za-z]+)/$', views.confirm_view,
        name='registration_confirm'),

    url(r'^accounts/register/$', views.registration_view, name='register'),
    url(r'^accounts/done/$', views.done_view, name='done'),
    url(r'^accounts/login/$', views.login_view, name='login'),
    url(r'^role_request/$', views.role_request_view, name='role_request'),
    url(r'^manage_requests/$', views.manage_requests_view, name='manage_requests'),

]


if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

robotom/robotom/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

admin.autodiscover()


urlpatterns = [

    url('', include('main.urls', namespace='main')),
    url(r'^experiment/', include('experiment.urls', namespace='experiment')),
    url(r'^storage/', include('storage.urls', namespace='storage')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

robotom/main/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

USER_ROLES = (
    ('ADM', u'Админ'),
    ('EXP', u'Экспериментатор'),
    ('RES', u'Исследователь'),
    ('GST', u'Гость'),
)

USER_GENDERS = (
    ('F', 'Женский'),
    ('M', 'Мужской'),
    ('N', 'Не указан')
)

USER_REQUESTS = (
    ('NONE', '-----'),
    ('ADM', u'Админ'),
    ('EXP', u'Экспериментатор'),
    ('RES', u'Исследователь'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    full_name = models.CharField('ФИО', max_length=100, blank=False)
    
    is_guest = models.BooleanField('Гость', default=True)
    is_admin = models.BooleanField('Админ', default=False)
    is_experimentator = models.BooleanField('Экспериментатор', default=False)
    is_researcher = models.BooleanField('Исследователь', default=False)
   
    gender = models.CharField('Пол', max_length=6, choices=USER_GENDERS, default='N')
    phone_number = models.CharField('Телефон', max_length=20, blank=True)
    address = models.CharField('Адрес', max_length=100, blank=True)
    work_place = models.CharField('Место учёбы/работы', max_length=100, blank=True)
    degree = models.CharField('Ученая степень', max_length=50, blank=True)
    title = models.CharField('Звание', max_length=50, blank=True)
    activation_key = models.CharField('Ключ активации', max_length=50, blank=True)

    def get_roles(self):
        if self.is_guest:
            return [u'Гость']
        roles = []
        if self.is_admin:
            roles.append(u'Админ')
        if self.is_experimentator:
            roles.append(u'Экспериментатор')
        if self.is_researcher:
            roles.append(u'Исследователь') 
        return roles 

    '''
    short role name, for example, 'RES' or 'ADM'
    '''
    def has_role(self, role):
        if role == 'NONE':
            return False
        return USER_ROLES[[role_tuple[0] for role_tuple in USER_ROLES].index(role)][1] in self.get_roles()

    '''
    long role name, for example, 'Исследователь'
    '''
    def has_role_long(self, role):
        return role in self.get_roles()

    def get_requests(self):
        return RoleRequest.objects.filter(user__pk=self.pk).exclude(role="NONE")

    def get_requested_roles(self):
        return [request.get_role_display() for request in self.get_requests()]


class RoleRequest(models.Model):
    user = models.ForeignKey(UserProfile)
    role = models.CharField('Запрос на изменение роли', max_length=15, choices=USER_REQUESTS, default='NONE')
    comment = models.TextField('Комментарий', max_length=300, blank=True)

robotom/main/forms.py
# -*- coding: utf-8 -*-

from main.models import UserProfile, RoleRequest
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ValidationError


class UserRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Имя пользователя *'
        self.fields['username'].widget = forms.TextInput(attrs={'placeholder': 'Имя пользователя'})
        self.fields['password1'].label = 'Пароль *'
        self.fields['password1'].widget = forms.PasswordInput(attrs={'placeholder': 'Пароль'})
        self.fields['password2'].label = 'Подтверждения пароля *'
        self.fields['password2'].widget = forms.PasswordInput(attrs={'placeholder': 'Подтверждение пароля'})

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError(u'Пользователь с таким email адресом уже зарегистрирован')
        return email

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

    email = forms.EmailField(required=True, label='Email *', widget=forms.TextInput(attrs={'placeholder': 'Email'}))


class UserProfileRegistrationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].label = 'ФИО *'
        self.fields['full_name'].widget = forms.TextInput(attrs={'placeholder': 'Иван Иванович Иванов'})

    def clean_full_name(self):
        full_name = self.cleaned_data.get('full_name')
        if not full_name:
            raise forms.ValidationError(u'Это поле обязательно')
        return full_name

    class Meta:
        model = UserProfile
        exclude = ('user', 'role', 'activation_key', 'is_admin', 'is_guest', 'is_experimentator', 'is_researcher')


class UserProfileFormEnabled(UserProfileRegistrationForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileFormEnabled, self).__init__(*args, **kwargs)


class UserProfileFormDisabled(UserProfileFormEnabled):
    def __init__(self, *args, **kwargs):
        super(UserProfileFormDisabled, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'disabled'
            self.fields[field].widget.attrs['readonly'] = 'readonly'
            self.fields[field].widget.attrs['placeholder'] = ''


class UserRoleRequestForm(forms.ModelForm):
    class Meta:
        model = RoleRequest
        exclude = ('user',)


class InactiveAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(InactiveAuthenticationForm, self).__init__(*args, **kwargs)

    def clean(self):
        try:
            return super(InactiveAuthenticationForm, self).clean()
        except ValidationError as e:
            if self.user_cache is not None:  # user exists but is not active
                return self.cleaned_data
            else:
                raise e

robotom/main/views.py
# -*- coding: utf-8 -*-
import json

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import login as auth_login, authenticate
from forms import UserRegistrationForm, UserProfileRegistrationForm, UserRoleRequestForm, UserProfileFormDisabled, \
    UserProfileFormEnabled, InactiveAuthenticationForm
from models import UserProfile, RoleRequest
from django.core.mail import send_mail
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib import messages
import logging
import hashlib
import datetime
import random
import requests
from django.forms import ValidationError

main_logger = logging.getLogger('main_logger')


def index(request):
    host_is_secure = 'https' if request.is_secure() else 'not https'
    return render(request, 'main/index.html', {'caption': 'ROBO-TOM', 'host_is_secure': host_is_secure})


@login_required
def group1(request):
    return render(request, 'main/group_1.html', {'caption': 'Группа 1'})


@login_required
def group2(request):
    return render(request, 'main/group_2.html', {'caption': "Группа 2"})


@login_required
def group3(request):
    return render(request, 'main/group_3.html', {'caption': "Группа 3"})


def confirm_view(request, activation_key):
    userprofile = get_object_or_404(UserProfile, activation_key=activation_key)
    userprofile.user.backend = 'django.contrib.auth.backends.ModelBackend'
    auth_login(request, userprofile.user)
    userprofile.user.is_active = True
    userprofile.user.save()
    messages.success(request, 'Ваш профиль был успешно подтверждён!')
    return redirect(reverse('main:role_request'))


'''
Making attempt to send user data to another module.
If everything is OK, returns None, else returns redirect to error page
'''


def try_user_sending(request, err_text, address, user=None, user_info=None):
    if not settings.REQUEST_DEBUG:
        if not user_info:
            user_info = json.dumps({'username': user.username, 'password': user.password, 'role': 'GST'})
        try:
            answer = requests.post(address, user_info, timeout=1)
            if answer.status_code != 200:
                messages.warning(request, u'{}. Модуль "Хранилище" завершил работу с кодом ошибки {}'
                                 .format(err_text, answer.status_code))
                main_logger.error(
                    u'{}. Модуль "Хранилище" завершил работу с кодом ошибки {}'.format(err_text, answer.status_code))
                return redirect(reverse('main:done'))
        except requests.exceptions.Timeout as e:
            messages.warning(request, 'Нет ответа от модуля "Хранилище". {}.'.format(err_text))
            main_logger.error(e)
            return redirect(reverse('main:done'))
        except BaseException as e:
            main_logger.error(e)
            messages.warning(request,
                             'Ошибка связи с модулем "Хранилище", невозможно сохранить данные. Возможно, отсутствует \
                             подключение к сети. Попробуйте позже или свяжитесь с администратором')
            return redirect(reverse('main:done'))
    return None


def registration_view(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        userprofile_form = UserProfileRegistrationForm(request.POST)
        if user_form.is_valid() and userprofile_form.is_valid():
            user = user_form.save(commit=False)
            user.is_active = False
            new_profile = userprofile_form.save(commit=False)

            #attempt = try_user_sending(request, u'Невозможно завершить регистрацию', settings.STORAGE_CREATE_USER_HOST,
            #                           user=user)

            #if attempt:  # if something went wrong
            #    return attempt

            user.save()

            salt = hashlib.sha1(str(random.random())).hexdigest()[:5]
            activation_key = hashlib.sha1(salt + user.email).hexdigest()
            new_profile.user = user
            new_profile.activation_key = activation_key
            activation_link = u'{}/accounts/confirm/{}'.format(request.get_host(), activation_key)
            email_subject = '[Томограф] Подтверждение регистрации'
            email_body = u"Приветствуем Вас на сайте Robo-Tom, {}!\n\
             Для активации аккаунта пройдите по следующей ссылке: {}".format(user.username, activation_link)

            try:
                send_mail(email_subject, email_body, 'robotomproject@gmail.com',
                          [user.email], fail_silently=False)
            except BaseException as e:
                import traceback
                main_logger.error(traceback.print_exc()) 
                main_logger.error(e)  
                messages.warning(request,
                                 'Произошла ошибка при отправке письма о подтверждении регистрации. Попробуйте \
                                 зарегистрироваться повторно, указав корректный email')
            else:
                messages.success(request,
                                 'На указанный Вами адрес было отправлено письмо. Для завершения регистрации и \
                                 подтверждения адреса перейдите по ссылке, указанной в письме')
            new_profile.save()
            userprofile_form.save_m2m()
            return redirect(reverse('main:done'))
        else:
            return render(request, 'registration/registration_form.html', {
                'user_form': user_form,
                'userprofile_form': userprofile_form,
                'caption': 'Регистрация'
            })

    return render(request, 'registration/registration_form.html', {
        'user_form': UserRegistrationForm(),
        'userprofile_form': UserProfileRegistrationForm(),
        'caption': 'Регистрация'
    })


def login_view(request):
    if request.method == 'POST':
        login_form = InactiveAuthenticationForm(data=request.POST)
        if login_form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                auth_login(request, user)
                return redirect(reverse('main:profile'))
            else:
                return render(request, 'registration/login.html', {
                    'form': login_form,
                    'caption': 'Вход на сайт'
                })
        else:
            return render(request, 'registration/login.html', {
                'form': login_form,
                'caption': 'Вход на сайт'
            })
    else:
        return render(request, 'registration/login.html', {
            'form': InactiveAuthenticationForm(),
            'caption': 'Вход на сайт'
        })


def done_view(request):
    return render(request, 'main/done.html', {'caption': 'Успех'})


@login_required
def profile_view(request):
    if request.method == 'POST':
        if 'resend' in request.POST:
            user = request.user
            salt = hashlib.sha1(str(random.random())).hexdigest()[:5]
            activation_key = hashlib.sha1(salt + user.email).hexdigest()
            new_profile = user.userprofile
            new_profile.activation_key = activation_key
            activation_link = u'{}/accounts/confirm/{}'.format(request.get_host(), activation_key)
            email_subject = '[Томограф] Подтверждение регистрации'
            email_body = u"Приветствуем Вас на сайте Robo-Tom, {}!\n Для активации аккаунта пройдите по следующей \
            ссылке: {}".format(user.username, activation_link)

            try:
                send_mail(email_subject, email_body, 'robotomproject@gmail.com',
                          [user.email], fail_silently=False)
            except BaseException:
                messages.warning(request,
                                 'Произошла ошибка при отправке письма о подтверждении регистрации. Попробуйте \
                                 зарегистрироваться повторно, указав корректный email')
            else:
                messages.success(request,
                                 'На указанный Вами адрес было повторно отправлено письмо. Для завершения регистрации \
                                 и подтверждения адреса перейдите по ссылке, указанной в письме')
            new_profile.save()
            return redirect(reverse('main:done'))
        if 'edit_profile' in request.POST:
            return render(request, 'main/profile.html', {
                'caption': u'Профиль пользователя {}'.format(request.user.username),
                'profile_form': UserProfileFormEnabled(instance=request.user.userprofile),
                'mode': 'edit',
            })
        elif 'save_profile' in request.POST:
            userprofile_form = UserProfileFormEnabled(request.POST, instance=request.user.userprofile)
            if userprofile_form.is_valid():
                profile = userprofile_form.save(commit=False)
                user_info = json.dumps({'username': profile.user.username, 'password': profile.user.password,
                                        'role': ', '.join(profile.get_roles())})
                #attempt = try_user_sending(request, u'Невозможно сохранить изменения профиля',
                #                           settings.STORAGE_ALT_USER_HOST, user_info=user_info)
                #if attempt:  # if something went wrong
                #    return attempt
                profile.save()
                messages.success(request, 'Ваши данные были успешно сохранены!')
        elif 'cancel' in request.POST:
            messages.success(request, 'Изменений в профиль не было внесено')
    else:
        if not request.user.is_active:
            messages.info(request,

robotom/main/templates/main/done.html
{% extends "base.html" %}

{% block content %}

    <div class="row">
        {% for message in messages %}
            <div class="col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-3">
                <div class="alert alert-{% if message.tags %}{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %}{% else %}info{% endif %}">
                    <a class="close" data-dismiss="alert" href="{% url 'storage:index' %}">&times;</a>
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

robotom/main/templates/main/empty.html
{% extends "base.html" %}

{% block content %}
    Здесь тлен и тишина, ведь это всего лишь заглушка для страницы. <br>
    Не желаешь ли ты реализовать это, %username%?
{% endblock content %}

robotom/main/templates/main/manage_requests.html
{% extends "base.html" %}

{% block content %}
    <style>
        DIV.table {
            display: table;
            border-collapse: collapse;
            margin: 10px;
            width: 900px;
        }

        FORM.tr, DIV.tr {
            display: table-row;
        }

        SPAN.td {
            display: table-cell;
            vertical-align: middle;
            padding: 6px;
            border: 1px solid grey;
        }

        SPAN.td-head {
            display: table-cell;
            vertical-align: middle;
            padding: 6px;
            font-weight: bold;
            border: 1px solid grey;
        }

        SPAN.td-comment {
            display: table-cell;
            vertical-align: middle;
            width: 40%;
            border: 1px solid grey;
        }

        SPAN.td-button {
            display: table-cell;
            vertical-align: middle;
            width: 5px;
        }
    </style>

    {% if messages %}
        <div class="row">
            {% for message in messages %}
                <div class="col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-3">
                    <div class="alert alert-{% if message.tags %}{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %}{% else %}info{% endif %}">
                        <a class="close" data-dismiss="alert" href="{% url 'storage:index' %}">&times;</a>
                        {{ message }}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <div align="center">
        {% if request_list %}
            <div align="center" class="table">
                <div class="tr">
                    <span class="td-head">Логин</span>
                    <span class="td-head">ФИО</span>
                    <span class="td-head">Текущая роль</span>
                    <span class="td-head">Запрос роли</span>
                    <span class="td-head">Дополнительная информация</span>
                    <span class="td-button"></span>
                    <span class="td-button"></span>
                </div>
                {% for request in request_list %}
                    <form class="tr" method="post" action="" name="{{ request.id }}_user_table">
                        {% csrf_token %}
                        <input type="hidden" name="request_id" value="{{ request.id }}"/>
                        <span class="td">{{ request.user.user.username }}</span>
                        <span class="td">{{ request.user.full_name }}</span>
                        <span class="td">{{ request.user.get_roles|join:", " }}</span>
                        <span class="td">{{ request.get_role_display }}</span>
                        <span class="td-comment">{{ request.comment }}</span>
                        <span class="td-button"><button type="submit" class="btn btn-success" style="margin-left: 5px"
                                                        name="accept">Принять
                        </button></span>
                        <span class="td-button"><button type="submit" class="btn btn-danger" style="margin-left: 5px"
                                                        name="decline">Отклонить
                        </button></span>
                    </form>
                {% endfor %}
            </div>
        {% else %}
            Поздравляем! На данный момент нет пользователей, ожидающих смены статуса.
        {% endif %}
    </div>
{% endblock content %}

robotom/main/templates/main/profile.html
{% extends "base.html" %}

{% block content %}
    {% load bootstrap3 %}
    {% load staticfiles %}

    {% if messages %}
        <div class="row">
            {% for message in messages %}
                <div class="col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-3">
                    <div class="alert alert-{% if message.tags %}{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %}{% else %}info{% endif %}">
                        {{ message }}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% if user.is_active %}
        {% for field in profile_form %}
            {% if field.errors %}
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-3">
                        <div class="alert alert-warning">
                            {{ field.errors }}
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h1 class="panel-title"><strong>Профиль пользователя {{ user.username }}</strong></h1>
                    </div>
                    <div class="panel-body" style="margin:15px">
                        <p>Ваши подтверждённые роли: <strong>{{ user.userprofile.get_roles|join:", "  }}</strong>.
                        </p>
                        {% if user.userprofile.get_requests %}
                            <p>Ваш запрос на присвоение ролей:
                                <strong>{{ user.userprofile.get_requested_roles|join:", " }}</strong> ещё
                                не был рассмотрен администратором.</p>
                        {% endif %}
                        <p>Вы можете <a href="{% url 'main:role_request' %}">послать новую заявку на изменение Вашей
                            роли на сайте</a> или <a href="{% url 'password_change' %}">изменить пароль</a>.</p>

                        {% if mode == 'view' %}
                            <form action="" method="post" class="form-horizontal" role="form">
                            {% csrf_token %}
                            <br>
                            {% for field in profile_form %}
                                <div class="form-group" style="padding-bottom:10px; border-bottom:1px solid LightGrey">
                                    <label class="control-label col-sm-4" style="padding:0px; color:#4F4F4F">
                                        {% if field.label|slice:"-1:" == '*' %}
                                            {{ field.label|slice:":-2" }}:
                                        {% else %}
                                            {{ field.label }}:
                                        {% endif %}
                                    </label>

                                    <div class="col-sm-6">
                                        <p class="form-control-static" style="padding:0">
                                            {% if field.value %}
                                                {% if field.name == 'gender' %}
                                                    {% if field.value == 'N' %}
                                                        <span style='color:grey; padding:0px'><i>Нет данных</i></span>
                                                    {% else %}
                                                        {{ user.userprofile.get_gender_display }}
                                                    {% endif %}
                                                {% else %}
                                                    {{ field.value }}
                                                {% endif %}
                                            {% else %}
                                                <span style='color:grey; padding:0px'><i>Нет данных</i></span>
                                            {% endif %}
                                        </p>
                                    </div>
                                </div>
                            {% endfor %}
                            <br>
                            {% buttons %}
                                <div style="text-align:center">
                                    <button type="submit" name="edit_profile" class="btn btn-primary btn-lg">Изменить
                                        данные
                                    </button>
                                </div>
                            {% endbuttons %}

                        {% else %}
                            <form action="" method="post" class="form">
                            {% csrf_token %}
                            {% bootstrap_form profile_form %}

                            {% buttons %}
                                <button type="submit" name="save_profile" class="btn btn-primary"
                                        style="margin-left: 15px">Сохранить
                                </button>
                                <button type="submit" name="cancel" class="btn btn-default" style="margin-left: 15px">
                                    Отмена
                                </button>
                            {% endbuttons %}
                        {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

robotom/main/templates/main/role_request.html
{% extends "base.html" %}

{% block content %}
    {% load bootstrap3 %}
    {% load staticfiles %}

    {% if messages %}
        <div class="row">
            {% for message in messages %}
                <div class="col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-3">
                    <div class="alert alert-{% if message.tags %}{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %}{% else %}info{% endif %}">
                        <a class="close" data-dismiss="alert" href="{% url 'storage:index' %}">&times;</a>
                        {{ message }}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% if user.is_active %}
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h1 class="panel-title"><strong>Запрос на изменение роли</strong></h1>
                    </div>
                    <div class="panel-body">
                        <div>Вы можете сделать запрос на получение прав на дополнительные действия на сайте.
                            Для этого выберите нужную роль из списка ниже.
                        </div>
                        <div>Если для принятия решения администратору требуется дополнительная информация о Вас,
                            оставьте её в поле "комментарий".
                        </div>
                        <br>

                        <form action="" method="post" class="form">
                            {% csrf_token %}
                            {% bootstrap_form role_form %}
                            {% buttons %}
                                <button type="submit" name="submit" class="btn btn-primary" style="margin-left: 15px">
                                    Запросить изменение роли
                                </button>
                                <button type="submit" name="cancel" class="btn btn-default" style="margin-left: 15px">
                                    Отмена
                                </button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}