robotom/experiment/urls.py
from django.conf.urls import url
from experiment import views

urlpatterns = [

    url(r'^$', views.experiment_view, name='index'),
    url(r'^adjustment/$', views.experiment_adjustment, name='index_adjustment'),
    url(r'^interface/$', views.experiment_interface, name='index_interface'),
    url(r'^tomograph/(?P<value_to_get>\S+)/$', views.experiment_tomograph, name='index_tomograph'),

]

robotom/main/urls.py
from django.conf.urls import url
from django.conf import settings
from main import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^group1/', views.group1, name='group_1'),
    url(r'^group2/', views.group2, name='group_2'),
    url(r'^group3/', views.group3, name='group_3'),

    url(r'^accounts/profile/$', views.profile_view, name='profile'),
    url(r'^accounts/confirm/(?P<activation_key>[0-9A-Za-z]+)/$', views.confirm_view,
        name='registration_confirm'),

    url(r'^accounts/register/$', views.registration_view, name='register'),
    url(r'^accounts/done/$', views.done_view, name='done'),
    url(r'^accounts/login/$', views.login_view, name='login'),
    url(r'^role_request/$', views.role_request_view, name='role_request'),
    url(r'^manage_requests/$', views.manage_requests_view, name='manage_requests'),

]


if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

robotom/robotom/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

admin.autodiscover()


urlpatterns = [

    url('', include('main.urls', namespace='main')),
    url(r'^experiment/', include('experiment.urls', namespace='experiment')),
    url(r'^storage/', include('storage.urls', namespace='storage')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

robotom/experiment/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

TOMO_STATES = (
    ('unavailable', 'unavailable'),
    ('ready', 'ready'),
    ('experiment', 'experiment'),
)


class Tomograph(models.Model):
    state = models.CharField(max_length=12, default='unavailable', choices=TOMO_STATES)

robotom/experiment/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.messages import get_messages
from django.core.files.storage import default_storage
from django.http import HttpResponse

from models import Tomograph
from requests.exceptions import Timeout
from functools import wraps

import logging
import hashlib
import random
import requests
import tempfile
import os
import json
import uuid
import time
import datetime

experiment_logger = logging.getLogger('experiment_logger')

GET_VOLT = 'get-voltage'
GET_CURR = 'get-current'
GET_VERT = 'get-vertical-position'
GET_HOR = 'get-horizontal-position'
GET_ANGL = 'get-angle-position'
GET_SHUT = 'get-shutter-state'

TOMO_NUM = 1

remote_url_settings = {
        GET_VOLT: settings.EXPERIMENT_SOURCE_GET_VOLT.format(TOMO_NUM),
        GET_CURR: settings.EXPERIMENT_SOURCE_GET_CURR.format(TOMO_NUM),
        GET_VERT: settings.EXPERIMENT_MOTOR_GET_VERT.format(TOMO_NUM),
        GET_HOR: settings.EXPERIMENT_MOTOR_GET_HORIZ.format(TOMO_NUM),
        GET_ANGL: settings.EXPERIMENT_MOTOR_GET_ANGLE.format(TOMO_NUM),
        GET_SHUT: settings.EXPERIMENT_SHUTTER_GET_STATUS.format(TOMO_NUM),
    }

tomo_path = '../tomograph/{}/'

local_url_settings = {
        'get_voltage_url': tomo_path.format(GET_VOLT),
        'get_current_url': tomo_path.format(GET_CURR),
        'get_vert_url': tomo_path.format(GET_VERT),
        'get_horiz_url': tomo_path.format(GET_HOR),
        'get_angle_url': tomo_path.format(GET_ANGL),
        'get_shutter_url': tomo_path.format(GET_SHUT),
    }


def has_experiment_access(user):
    return user.userprofile.is_admin or user.userprofile.is_experimentator


def info_once_only(request, msg):
    storage = get_messages(request)
    if msg not in [m.message for m in storage]:
        messages.info(request, msg)


def migrations():
    if len(Tomograph.objects.all()) == 0:
        tomo = Tomograph(state='unavailable')
        tomo.save()


def try_request_post(request, address, content, source_page, stream=False):
    result = {'response_dict': None, 'error': None}
    try:
        answer = requests.post(address, content, timeout=settings.TIMEOUT_DEFAULT, stream=stream) 
        result['response_dict'] = json.loads(answer.content)
        if answer.status_code != 200:
            messages.warning(request, u'Модуль "Эксперимент" завершил работу с кодом ошибки {}'.format(answer.status_code))
            experiment_logger.error(u'Модуль "Эксперимент" завершил работу с кодом ошибки {}'.format(answer.status_code))
            result['error'] = redirect(reverse(source_page))
    except Timeout as e:
        messages.warning(request, 'Нет ответа от модуля "Эксперимент".')
        experiment_logger.error(e)
        result['error'] = redirect(reverse(source_page))
    except BaseException as e:
        experiment_logger.error(e)
        messages.warning(request,
                         '''Ошибка связи с модулем "Эксперимент", невозможно сохранить данные.
                         Возможно, отсутствует подключение к сети.
                         Попробуйте снова через некоторое время или свяжитесь с администратором''')
        result['error'] = redirect(reverse(source_page))
    return result


def try_request_get(request, address, source_page=''):
    result = {'response_dict': None, 'error': None}
    try:
        answer = requests.get(address, timeout=settings.TIMEOUT_DEFAULT) 
        result['response_dict'] = json.loads(answer.content)
        if answer.status_code != 200:
            messages.warning(request, u'Модуль "Эксперимент" завершил работу с кодом ошибки {}'.format(answer.status_code))
            experiment_logger.error(u'Модуль "Эксперимент" завершил работу с кодом ошибки {}'.format(answer.status_code))
            if source_page:
                result['error'] = redirect(reverse(source_page))
            else:
                result['error'] = u'Модуль "Эксперимент" завершил работу с кодом ошибки {}'.format(answer.status_code)
    except Timeout as e:
        messages.warning(request, 'Нет ответа от модуля "Эксперимент"')
        experiment_logger.error(e)
        if source_page:
            result['error'] = redirect(reverse(source_page))
        else:
            result['error'] = 'Нет ответа от модуля "Эксперимент"'

    except BaseException as e:
        experiment_logger.error(e)
        messages.warning(request,
                         '''Ошибка связи с модулем "Эксперимент", невозможно сохранить данные.
                         Возможно, отсутствует подключение к сети.
                         Попробуйте снова через некоторое время или свяжитесь с администратором''')
        if source_page:
            result['error'] = redirect(reverse(source_page))
        else:
            result['error'] = '''Ошибка связи с модулем "Эксперимент", невозможно сохранить данные.
                                Возможно, отсутствует подключение к сети.
                                Попробуйте снова через некоторое время или свяжитесь с администратором'''


    return result


def check_result(result, request, tomo, success_msg=''):

    response_dict = result['response_dict']

    if response_dict['success']:
        if success_msg:
            messages.success(request, success_msg)
        tomo.save()
    else:
        experiment_logger.error(u'Модуль "Эксперимент" работает некорректно в данный момент. Попробуйте позже {}'.format(
                    response_dict['error']))
        messages.warning(request, 
            u'Модуль "Эксперимент" работает некорректно в данный момент. Попробуйте позже {}'.format(response_dict['error']))


def set_current_state_msg(request, tomo):
    if tomo.state == 'unavailable':
        info_once_only(request, u'Текущее состояние томографа: недоступен')
    elif tomo.state == 'ready':
        info_once_only(request, u'Текущее состояние томографа: ожидание')
    elif tomo.state == 'experiment':
        info_once_only(request, u'Текущее состояние томографа: эксперимент')


def get_current_state(request, tomo):
    try:
        result = try_request_get(request, settings.EXPERIMENT_GET_STATE.format(TOMO_NUM))
        if result['error']:
            tomo.state = 'unavailable'
        else:
            response_dict = result['response_dict']
            tomo.state = response_dict['result']
    except BaseException as e:
        tomo.state = 'unavailable'
    tomo.save()


def update_state_before_run(view):
    @wraps(view)
    def wrapped(request, *args, **kwargs):
        tomo = get_object_or_404(Tomograph, pk=1)
        get_current_state(request, tomo)
        set_current_state_msg(request, tomo)
        result = view(request, *args, **kwargs)
        return result
    return wrapped


@login_required
@user_passes_test(has_experiment_access)
def experiment_view(request):

    migrations()

    tomo = get_object_or_404(Tomograph, pk=1)
    result = None
    success_msg = ''
    source_page = 'experiment:index'

    if request.method == 'POST':
        if 'on_exp' in request.POST:
            success_msg = u'Томограф включен'
            result = try_request_get(request, settings.EXPERIMENT_SOURCE_POWER_ON.format(TOMO_NUM), source_page)

        if 'of_exp' in request.POST:
            success_msg = u'Томограф выключен'
            result = try_request_get(request, settings.EXPERIMENT_SOURCE_POWER_OFF.format(TOMO_NUM), source_page)

    if result:
        if result['error']:
            return result['error']
        check_result(result, request, tomo, success_msg)

    get_current_state(request, tomo)
    set_current_state_msg(request, tomo)
    return render(request, 'experiment/start.html', {
        'caption': 'Эксперимент',
        'tomograph': tomo,
    })


@update_state_before_run
@login_required
@user_passes_test(has_experiment_access)
def experiment_adjustment(request):

    migrations()

    js_urls = {k: request.build_absolute_uri(v) for k, v in local_url_settings.iteritems()}

    # force https in urls — kludged until build_absolute_uri not return correct protocol
    host = request.get_host()
    prod = ('127.0.0.1' not in host) and ('localhost' not in host)
    if prod:
        js_urls = {k: force_https(v) for k, v in js_urls.iteritems()}
    # end of force https kludge

    js_url_settings = json.dumps(js_urls)

    tomo = get_object_or_404(Tomograph, pk=1)
    result = None
    success_msg = ''
    source_page = 'experiment:index_adjustment'

    if request.method == 'POST':
        if 'move_hor_submit' in request.POST:
            info = json.dumps(int(request.POST['move_hor']))
            result = try_request_post(request, settings.EXPERIMENT_MOTOR_SET_HORIZ.format(TOMO_NUM), info, source_page)
            success_msg = u'Горизонтальное положение образца изменено'

        if 'move_ver_submit' in request.POST: 
            info = json.dumps(int(request.POST['move_ver']))
            result = try_request_post(request, settings.EXPERIMENT_MOTOR_SET_VERT.format(TOMO_NUM), info, source_page)
            success_msg = u'Вертикальное положение образца изменено'

        if 'rotate_submit' in request.POST: 
            info = json.dumps(float(request.POST['rotate']))
            result = try_request_post(request, settings.EXPERIMENT_MOTOR_SET_ANGLE.format(TOMO_NUM), info, source_page)
            success_msg = u'Образец повернут'

        if 'reset_submit' in request.POST: 
            result = try_request_get(request, settings.EXPERIMENT_MOTOR_RESET_ANGLE.format(TOMO_NUM), source_page)
            success_msg = u'Текущий угол поворота принят за 0'

        if 'text_gate' in request.POST:
            if request.POST.get('gate_state', None) == 'open':
                result = try_request_get(request, settings.EXPERIMENT_SHUTTER_OPEN.format(TOMO_NUM), source_page)

robotom/experiment/templates/experiment/interface.html
{% extends "base.html" %}

{% block content %}
   {% if messages %}
        <div class="row">
            {% for message in messages %}
                <div class="col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-3">
                    <div class="alert alert-{% if message.tags %}{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %}{% else %}info{% endif %}">
                        {{ message }}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Эксперимент</h3>

            </div>
            <div class="panel-body">

                <form name="manual" method="POST">
                    <div class="control-group">
                        {% csrf_token %}
                        <h3>Параметры образца</h3>

                        <div class="row">
                            <div class="col-xs-12 col-md-4">
                                <label for="name">Название образца</label>

                                <input type="text" class="form-control ntSaveForms"
                                       id="name" name="name"
                                       placeholder="Название образца">
                            </div>
                            <div class="col-xs-12 col-md-4">
                                <label for="type">Теги</label>

                                <input type="text" class="form-control ntSaveForms" id="type" name="tags"
                                       placeholder="Теги">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-6">
                                <h3>Кадры DARK</h3>
                            </div>
                            <div class="col-xs-6">
                                <h3>Кадры EMPTY</h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-3">
                                <label for="dark_quantity">Количество</label>
                            </div>
                            <div class="col-xs-3">
                                <label for="dark_exposure">Экспозиция, мс</label>
                            </div>
                            <div class="col-xs-3">
                                <label for="empty_quantity">Количество</label>
                            </div>
                            <div class="col-xs-3">
                                <label for="empty_exposure">Экспозиция, мс</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-3 col-md-3">
                                <input type="number" step="1" min="0" id="dark_quantity"
                                       class="form-control ntSaveForms" name="dark_quantity" placeholder="Количество">
                            </div>
                            <div class="col-xs-3 col-md-3">
                                <input type="number" step="10" min="10" max="100000" class="form-control ntSaveForms"
                                       id="dark_exposure" name="dark_exposure"
                                       placeholder="Экспозиция">
                            </div>
                            <div class="col-xs-3 col-md-3">
                                <input type="number" step="1" min="0" id="empty_quantity"
                                       class="form-control ntSaveForms" name="empty_quantity" placeholder="Количество">
                            </div>
                            <div class="col-xs-3 col-md-3">
                                <input type="number" step="10" min="10" max="100000" class="form-control ntSaveForms"
                                       id="empty_exposure" name="empty_exposure"

                                       placeholder="Экспозиция">
                            </div>
                        </div>


                        <h3>Кадры DATA</h3>

                        <div class="row">
                            <div class="col-xs-3">
                                <label for="data_shots_quantity">Количество</label>
                            </div>
                            <div class="col-xs-3">
                                <label for="data_shots_exposure">Экспозиция, мс</label>
                            </div>
                            <div class="col-xs-3">
                                <label for="data_angle">Угловой шаг, градусы</label>
                            </div>
                            <div class="col-xs-3">
                                <label for="data_same">Кадров на угол поворота</label>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-3">

                                <input type="number" step="1" min="0" id="data_shots_quantity"
                                       class="form-control ntSaveForms" name="data_shots_quantity"
                                       placeholder="Количество">
                            </div>
                            <div class="col-xs-3">
                                <input type="number" step="10" min="10" max="100000" class="form-control ntSaveForms"
                                       id="data_shots_exposure" name="data_shots_exposure"
                                       placeholder="Экспозиция">
                            </div>

                            <div class="col-xs-3">
                                <input type="number" step="0.01" id="data_angle" class="form-control ntSaveForms"
                                       name="data_angle" placeholder="Угловой шаг">
                            </div>
                            <div class="col-xs-3">
                                <input type="number" step="1" min="0" class="form-control ntSaveForms" id="data_same"
                                       name="data_same" placeholder="Количество кадров">
                            </div>
                        </div>

                        <br>
                        <input type="submit" style="white-space:normal" class="btn btn-success btn-lg"
                               name="parameters" value="Начать эксперимент"
                                {% if user.is_authenticated and user.userprofile.is_experimentator and tomograph.state == "ready" %} {% else %}
                               disabled {% endif %}>

                        <input type="submit" style="white-space:normal" class="btn btn-default btn-lg"
                               name="turn_down" value="Закончить эксперимент"
                                {% if user.is_authenticated and user.userprofile.is_experimentator and tomograph.state == "experiment" %} {% else %}
                               disabled {% endif %}>

                    </div>
                </form>
            </div>
        </div>
    </div>
    {% load staticfiles %}

    <script type='text/javascript' src="{% static 'experiment/js/ntsaveforms.js' %}"></script>

{% endblock content %}

robotom/experiment/templates/experiment/start.html
{% extends "base.html" %}

{% block content %}
    {% if messages %}
        <div class="row">
            {% for message in messages %}
                <div class="col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-3">
                    <div class="alert alert-{% if message.tags %}{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %}{% else %}info{% endif %}">
                        {{ message }}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="container">
        <div class="panel panel-default">

            <div class="panel-heading">
                <h3>Эксперимент</h3>
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <h4> Изменить состояние томографа </h4>
                        <form method="POST" action="">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-default btn-md" name="on_exp"
                                   value="Включить источник" style="white-space:normal"
                                    {% if user.is_authenticated and user.userprofile.is_experimentator and tomograph.state == "ready" %} {% else %}
                                   disabled {% endif %}>

                            {% csrf_token %}
                            <input type="submit" name="of_exp" class="btn btn-default btn-md"
                                   value="Выключить источник" style="white-space:normal"
                                    {% if user.is_authenticated and user.userprofile.is_experimentator and tomograph.state == "ready" %} {% else %}
                                   disabled {% endif %}>
                        </form>
                    </div>

                    <div class="col-xs-12 col-md-6">
                        <h4> Изменить параметры </h4>
                        <a class="btn btn-default btn-md" href="{% url 'experiment:index_adjustment' %}"
                           style="white-space:normal">Параметры томографа</a>
                        <a class="btn btn-default btn-md" href="{% url 'experiment:index_interface' %}"
                           style="white-space:normal">Параметры эксперимента</a>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}